server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**
          filters:
            - AuthenticationFilter


        - id: address-service
          uri: lb://ADDRESS-SERVICE
          predicates:
            - Path=/address/**
          filters:
            - AuthenticationFilter


        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter


        - id: security-service2
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/api/v1/**
          filters:
            - AuthenticationFilter


        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
          filters:
            - AuthenticationFilter


        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservations/**
          filters:
            - AuthenticationFilter


        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - AuthenticationFilter


        - id: payment2-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/balance/**
          filters:
            - AuthenticationFilter


        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review/**
          filters:
            - AuthenticationFilter


        - id: pricing-service
          uri: lb://PRICING-SERVICE
          predicates:
            - Path=/price/**
          filters:
            - AuthenticationFilter


        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/room/**
          filters:
            - AuthenticationFilter


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
