server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - name: AuthenticationFilter
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**



        - id: address-service
          uri: lb://ADDRESS-SERVICE
          predicates:
            - Path=/address/**


        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/auth/**
        #


        - id: security-service2
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/api/v1/**



        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**



        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservations/**


        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**


        - id: payment2-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/balance/**


        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review/**


        - id: pricing-service
          uri: lb://PRICING-SERVICE
          predicates:
            - Path=/price/**


        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/room/**
#          filters:
#            - AuthenticationFilter


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


